import Head from "next/head";

interface HeadProps {
  subtitle?: string;
}

export default function HeadComponent({ subtitle }: HeadProps) {
  return (
    <Head>
      <title>enBonnet{subtitle ? ` - ${subtitle}` : null}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
