import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import { ArrayOfPosts, ArticleType } from "@/types/ArticleType";
import { POSTS_SORT_BY_CREATED_AT_DESC } from "@/lib/api";
import slugify from "@/lib/slugify";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>enBonnet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={""}>
        {posts.map((post) => (
          <div key={post.id}>
            <Link href={`/post/${post.slug}`}>
              <a>{post.title}</a>
            </Link>
          </div>
        ))}
      </main>

      <footer className={""}>Footer</footer>
    </div>
  );
}

export async function getStaticProps() {
  const res: ArrayOfPosts = await axios.get(POSTS_SORT_BY_CREATED_AT_DESC);
  const posts = res.data
    .filter((article: ArticleType) => article.publico)
    .map((post: ArticleType) => ({
      ...post,
      slug: slugify(post.title),
    }));
  return {
    props: { posts },
  };
}
