import Head from "next/head";

export default function Home({ posts }) {
  console.log(posts);

  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={""}>
        {posts.map((post) => (
          <div>{post.title}</div>
        ))}
      </main>

      <footer className={""}>Footer</footer>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://enbonnet-cms.herokuapp.com/articles?_sort=created_at:desc"
  );
  console.log(res);
  return {
    props: { posts: [] },
  };
}
